### ISSUE TITLE
There is an issue with recommended jobs in matches webpage

### ISSUE THREAD

**Issue by rohanajm7** [jashgopani/application-tracking-system#11]
In the matches webpage, the frontend from react cannot load the matched jobs. In my case, React cannot render the page only.
Here is the screenshot,
![image](https://github.com/jashgopani/application-tracking-system/assets/66876265/4d9da2c2-e392-4515-a4d2-a4b50c1ca775)

**Comment by jashgopani** [comment]
This issue is resolved in PR #18
