### ISSUE TITLE
Location list needs to be updated

### ISSUE THREAD

**Issue by jashgopani** [jashgopani/application-tracking-system#6]
While setting up the profile, I found the location list to be incomplete. The list needs to be more extensive.

<img width="611" alt="image" src="https://github.com/jashgopani/application-tracking-system/assets/40660648/03f99258-d390-45e3-be7e-2f2e3b5438d8">

**Comment by rohanajm7** [comment]
I was able to recreate the issue, it seems there has to be changes in the front-end code to add more locations.
