### ISSUE TITLE
Need a progress indicator

### ISSUE THREAD

**Issue by hemil26** [jashgopani/application-tracking-system#9]
Need a progress indicator when background operations are being performed.

**Comment by rohanajm7** [comment]
@hemil26 Please mention the webpage and the processes which need a progress indicator

**Comment by jashgopani** [comment]
Changing the label to enhancements since this is not a bug

**Comment by jashgopani** [comment]
Added progress indicator in matches screen as the background fetching work is prominent and needs some indication
